version: "3"
services:
  https-portal3000:
    image: steveltn/https-portal:1
    ports:
      - '3443:443'
    environment:
      STAGE: local
      DOMAINS: 'localhost -> http://host.docker.internal:8080'
